### PR TITLE
Review docs

### PR DESCRIPTION
**Pull request by eparejatobes**
There are a lot of typos.

### CODE REVIEW

**Comment by eparejatobes** [comment]
I'm on it

**Comment by eparejatobes** [comment]
I'm happy now. If anyone wants to review this, go for it.

**Review by laughedelic — APPROVED** [review]

**Comment by eparejatobes** [comment]
thanks @laughedelic

**Comment by eparejatobes** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/ohnosequences/db.rna16s/pull-request/62/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ohnosequences/db.rna16s)

**Comment by laughedelic** [comment]
Why is it closed?

**Comment by eparejatobes** [comment]
Weird. Looks like the merge failed locally or something.

LGTM

[Approved with PullApprove](https://pullapprove.com/ohnosequences/db.rna16s/pull-request/62/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ohnosequences/db.rna16s)

**Pull request merged**
