### PR TITLE
Review sequence quality filters

### PR DESCRIPTION
**Pull request by eparejatobes**
- [x] Drop sequences with some `N`
- [x] Drop sequences with ambiguous chars

### CODE REVIEW

**Comment by agarciamontoro** [comment]
> - [ ] Drop sequences with ambiguous chars

What do you mean by ambigous chars, @eparejatobes?

**Comment by agarciamontoro** [comment]
@eparejatobes, take a look at those two commits when you have a minute so we can merge this and start implementing the tests to upload to S3.

**Comment by eparejatobes** [comment]
LGTM.

**Pull request merged**
