### PR TITLE
Document the drop redundant assignments filter

### PR DESCRIPTION
**Pull request by laughedelic**

### CODE REVIEW

**Comment by laughedelic** [comment]
> _No description provided._

So https://github.com/ohnosequences/db.rna16s/pull/37/commits/1bccc3f18ad08fee1aed82bcccc5be0df000507b didn't help? Or what is this issue?

**Comment by eparejatobes** [comment]
https://github.com/ohnosequences/db.rna16s/pull/37#discussion_r72408232

**Comment by laughedelic** [comment]
Ok. I'm fixing https://github.com/ohnosequences/db.rna16s/pull/32#discussion_r71912023 first.

**Comment by laughedelic** [comment]
@eparejatobes review, please

**Comment by eparejatobes** [comment]
OK LGTM

**Pull request merged**
