### PR TITLE
Update to RNAcentral v7

### PR DESCRIPTION
**Pull request by laughedelic**
Depends on https://github.com/ohnosequences/db.rnacentral/issues/31

### CODE REVIEW

**Comment by laughedelic** [comment]
Updated it to RNAcentral v7, but haven't run the bundles yet.

**Comment by laughedelic** [comment]
Some things got broken on the way and I spent quite some time debugging it. Now the first 2 steps work fine, then in the MG7 launch fails on BLAST. Most likely it's a regression in Loquat or the sqs-bug again. I will try to fix it in Loquat and return then here.

**Comment by laughedelic** [comment]
@rtobes @eparejatobes 
The new DB based on RNAcentral v7 is ready. The data for your review is in 

* [s3://resources.ohnosequences.com/ohnosequences/db-rna16s/1.0.0-9-g0df2514/dropInconsistentAssignments/](https://s3.console.aws.amazon.com/s3/buckets/resources.ohnosequences.com/ohnosequences/db-rna16s/1.0.0-9-g0df2514/dropInconsistentAssignments/)

----

Things for me to finish here:
- [x] move fasta parsing fix to db.rnacentral code
- [ ] update dev-docs
- [ ] a big chain of releases starting from Loquat and ending here
- [ ] with some advances made in 3eb9b31 and `launchLocally` in Loquat, it's now possible to automate release process: #34

**Comment by rtobes** [comment]
Good news!
I am going to review

**Comment by eparejatobes** [comment]
Reviewing this is harder than it should. We need to generate fasta files and separate CSVs for

- entries who lost all assignments (and are thus dropped)
- entries with *some* removed assignments

Having the proportions of these would be helpful too.

**Comment by eparejatobes** [comment]
Nothing super-strange here, :+1: from me.

**Comment by rtobes** [comment]
Go ahead!

**Comment by laughedelic** [comment]
I'm merging this to release the reviewed data. The WIP on automated release and dependencies updates will be done in another PR(s).

**Comment by laughedelic** [comment]
The reviewed data has been released as 1.1.0-RC1. I will make the final release after the data generation process is automated.

**Pull request merged**
