### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by laughedelic**
See https://github.com/ohnosequences/db.rnacentral/issues/28

### CODE REVIEW

**Comment by laughedelic** [comment]
I guess, I can't avoid updating all dependencies here and in db.rnacentral. So I will have to make a new release of the data. Therefore 2 questions (to @eparejatobes):

- should I use the latest version of MG7? (M5 + fixes)
- can I remove the [`BlastDBType`](https://github.com/ohnosequences/db.rna16s/blob/master/src/main/scala/package.scala#L14) reference from the `Compile`-scope code here? It forces otherwise unnecessary (compile-)dependency on blast-api. The main point of moving everything to the `Test` scope is to have in `Compile` only the data reference (and minimal library dependencies).

**Review by eparejatobes — COMMENTED** [review]
1. removing the db type: OK
2. MG7 version: what's the state of it? they were just trivial issues?

**Comment by laughedelic** [comment]
> MG7 version: what's the state of it? they were just trivial issues?

I just finished running the test pipelines in https://github.com/ohnosequences/mg7/pull/105. So you can say after reviewing it, whether we want to use the latest MG7 here. 

Either way, MG7 will need updated dependencies not to conflict with the updates made here. For the latest MG7 I have https://github.com/ohnosequences/mg7/pull/121.

**Comment by laughedelic** [comment]
@eparejatobes do you want to change any MG7 parameters here?

**Comment by laughedelic** [comment]
@eparejatobes ⬆️ ?

**Comment by laughedelic** [comment]
I ran the first two steps:
- pick16SCandidates
- dropRedundantAssignments

I will wait for confirmation from @eparejatobes before running MG7 and further steps.

**Comment by eparejatobes** [comment]
Re https://github.com/ohnosequences/db.rna16s/pull/65#issuecomment-269014684

word size should be smaller, 150 is too much. Better set it to ~40, did it in 2c25a31.

**Review by eparejatobes — APPROVED** [review]

**Comment by laughedelic** [comment]
This is done. The new database (with all deps updated and RNAcentral 6.0) is in

```
s3://resources.ohnosequences.com/ohnosequences/db-rna16s/0.12.0-18-ge5e9e28/release/
```

(or intermediate results at `../`)

@eparejatobes Are you going to review this data?

**Comment by eparejatobes** [comment]
@laughedelic looks fine. LGTM.

[Approved with PullApprove](https://pullapprove.com/ohnosequences/db.rna16s/pull-request/65/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ohnosequences/db.rna16s)

**Review by eparejatobes — APPROVED** [review]

**Comment by laughedelic** [comment]
LGTM

**Comment by eparejatobes** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/ohnosequences/db.rna16s/pull-request/65/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ohnosequences/db.rna16s)

**Comment by laughedelic** [comment]
I cannot approve it. You're the only maintainer 😐

**Pull request merged**
