### PR TITLE
Filter out assignments covered by bigger sequences

### PR DESCRIPTION
**Pull request by laughedelic**
For each sequence filter out those assignments that appear in bigger sequences. This will make assignments more specific.

### CODE REVIEW

**Comment by eparejatobes** [comment]
what's the status of this?

**Comment by laughedelic** [comment]
No much progress, but I'm going to work on this on Monday.

**Comment by laughedelic** [comment]
😓  Sorry for the delay here, but this appeared to be more complicated than I expected. The difficulty is mostly caused by the requirement to collect both accepted _and discarded_ sequences/assignments. 

I finished implementation, tomorrow I will document/refactor the code and run tests.

**Comment by laughedelic** [comment]
This is done 👌 Here are some stats for each step:
- `filter1`: Filtering out unrelated sequences
  - results: `s3://resources.ohnosequences.com/era7bio/db.rna16s/0.8.0/filter1/`
  - 2,5-3 hours on `r3.2xlarge`
  - stats (FASTA sequences):
    - rejected: 9 022 570 
    - accepted: 366 679 
    - intersection: 3127 
- `filter2`: Filtering out assignments contained in another ones
  - results: `s3://resources.ohnosequences.com/era7bio/db.rna16s/0.8.0/filter2/`
  - ~**3** minutes on `m3.medium` (**!**)
  - stats (FASTA sequences):
    - rejected: 104 346  
    - accepted: 262 333
    
    (sums up to the accepted number from the previous filter)
- `generate`: Generating BlastDB
  - results: `s3://resources.ohnosequences.com/era7bio/db.rna16s/0.8.0/blastdb/`
  - ~1 minute on `m3.medium`

**Comment by marina-manrique** [comment]
So we could say that the 16S db has 262 333 sequences, right?

**Comment by laughedelic** [comment]
Exactly 👌

**Pull request merged**
