### PR TITLE
Filter based on the output of the MG7 assignment

### PR DESCRIPTION
**Pull request by laughedelic**
Run MG7 on the DB excluding matches of the subject sequence with itself in the reference. Then compare results with the assignments in the DB and drop those that are less specific than the ones we got from the MG7 run.
- `s` — sequence
- `DB(s) = { a_i | i }` — taxonomic assignments for `s` in the DB
- `MG7(s) = lca({x, y, z})` — assignment from the MG7 run
- drop those `a_i`, which are less specific than the `lca` from MG7

### CODE REVIEW

**Comment by laughedelic** [comment]
The MG7 pipeline is in https://github.com/ohnosequences/mg7/issues/77. Here will be the comparison/filtering of the results.

**Comment by laughedelic** [comment]
As I mentioned in https://github.com/ohnosequences/mg7/pull/77#issuecomment-224636121 results are in `s3://era7p/mg7-test/data/out/1.0.0-M4-3-g6baecfc/refdb/merge/` and what I see there immediately:
- ~30% of the output is no-hits, which means those sequences that are not matched with anything except of themselves 👌 (with the 100% `qcovs` and maximum `pident` filters)

**Comment by laughedelic** [comment]
I got some strange results here:

```
# wc -l ...
  262333 source/table.5.0.tsv
  152709 accepted/table.5.0.tsv
  111095 rejected/table.5.0.tsv
```

I thought that this filter cannot discard some sequence completely, only filter out some of the assigned taxas (but not all) "_
But it appears that there are 109624 _completely_ rejected sequences. 

@eparejatobes WDYT?

**Comment by eparejatobes** [comment]
Need a bit of context

**Comment by eparejatobes** [comment]
and samples

**Comment by laughedelic** [comment]
Check the original post: we're filtering those taxas in the id2taxas table that are less specific than the LCA that we got from running MG7 on the DB itself. 

I thought that each sequence just gets reduced number of "imprecise" taxa assignments, but it cannot be all of them. Now I think that it's possible because we exclude query sequence from the MG7 results, but it's still strange for me.

I'll rerun it and give you a link to the files. Here are a couple of them:

| ID | Original taxas | LCA from MG7 | LCA's name |
| :-- | :-- | :-- | :-- |
| URS0000484991 | 372660;372658;372657 | 1076 | Rhodopseudomonas palustris |
| URS000089517E | 1215914;998820;999378 | 498216 | Lactobacillus casei str. Zhang |

So the filter says that all these taxas are not descendants of the corresponding LCAs.

**Comment by eparejatobes** [comment]
and it's true. There are a lot of badly positioned strains, makes sense to me. I see two options:
1. be more stringent with pident, so that these cases would get no-hits
2. if the lca is only one level up (for example), don't discard the assignments

Or simply discard 'em all

**Comment by laughedelic** [comment]
For the first one (URS0000484991):
- the original taxas are
  - Rhodopseudomonas sp. TUT3621
  - Rhodopseudomonas sp. TUT3624
  - Rhodopseudomonas sp. TUT3627
- the LCA from MG7 is Rhodopseudomonas palustris (because we compare this sequence with the similar ones that are in the DB)
- they are both descendants of Rhodopseudomonas (1073)

**Comment by eparejatobes** [comment]
Yes, and in the original paper they just take Rhodopseudomonas palustris and build a new taxonomy using sequence similarity :laughing: https://www.jstage.jst.go.jp/article/jgam/55/6/55_6_469/_pdf

**Comment by laughedelic** [comment]
> 1. be more stringent with pident

pidents were `99.19` and `99.94` correspondingly

> 1. if the lca is only one level up

what do you mean?

I'm quite confused now with this filter. I think that we shouldn't exclude query sequence from the hits, so that we'll see the LCA of _this_ sequence _and_ the similar ones. Otherwise we're checking that this sequence's assignments are more specific than assignments of its cousins.. "_

**Comment by eparejatobes** [comment]
Anyway, even at 100% identity, we could have identical 16S seqs, and that's OK as long as they are "close".

**Comment by eparejatobes** [comment]
if you don't remove the query you won't be able to pick those sequences with wildly different assignments. It's just that we need to set it to be close, not necessarily below

**Comment by eparejatobes** [comment]
where close means in the path to the root, and less than `n` steps from

**Comment by laughedelic** [comment]
> It's just that we need to set it to be close, not necessarily below

Ok, this makes sense. But it's more involved. I'll continue with it tomorrow.

**Comment by eparejatobes** [comment]
In the rhodopseudomonas example:
1. In the original assignment we have three taxa, and their LCA is Rhodopseudomonas
2. the assignment through MG7 yields Rhodopseudomonas palustris
3. If we calculate the LCA of both, is Rhodopseudomonas (the genus) which is _close_ to the MG7 assignment (only one step up). This means that it is OK

**Comment by eparejatobes** [comment]
Note that setting the pident high enough means that you won't discard those species for which there are no 16S of close taxa.

**Comment by laughedelic** [comment]
I've implemented this. Now a taxa is filtered out if it's not a descendant of the mg7-lca's **parent**. Here are the results:

``` shell
#wc -l ...
262333 source/table.5.0.tsv
246736 accepted/table.5.0.tsv
 16502 rejected/table.5.0.tsv
```

i.e. now much less rejected sequences and only 905 in intersection (those that got some taxas rejected and some accepted).

Results are in `s3://resources.ohnosequences.com/era7bio/db.rna16s/0.9.0/filter3/`. Now I'm going to generate a new BlastDB from this output.

**Comment by eparejatobes** [comment]
Looks really good. Could you please add here all the discarded stuff?

**Comment by laughedelic** [comment]
> discarded stuff

It's there, called "rejected".. Or what do you mean? "_

**Comment by eparejatobes** [comment]
In the repo

**Comment by laughedelic** [comment]
I don't get it. Which repo?

**Comment by eparejatobes** [comment]
Don't worry

**Comment by laughedelic** [comment]
The BlastDB is at `s3://resources.ohnosequences.com/era7bio/db.rna16s/0.9.0/filter3/accepted/blastdb/`.
I will merge this, release and then write the docs on the whole DB generation workflow, as it's quite involved now (not complex, but needs some explanation).

**Comment by eparejatobes** [comment]
After looking at the results:
1. We are dropping obviously bad taxonomy assignments, like http://rnacentral.org/rna/URS0000543207?tab=taxonomy or http://rnacentral.org/rna/URS0000321FF1?tab=taxonomy. Good! :tada: 
2. For not so common taxa such as this one http://rnacentral.org/rna/URS00005B8513?tab=taxonomy I don't see any obvious reason to drop it. What was the pident threshold? probably not stringent enough, and then these rarer taxa get hits with distant ones and get discarded?

**Comment by laughedelic** [comment]
Pident threshold was 98%

**Comment by laughedelic** [comment]
@eparejatobes ok, so we talked with @rtobes and decided to leave unique assignments without any filter (as in the last case) and to try with higher pident (98.5? or 99.0?).

Also, the [second thing](http://rnacentral.org/rna/URS0000321FF1?tab=taxonomy) is strange, the taxonomy shown on the RNAcentral website is not a tree: on the lower branch there's the `Bacilli` node, but the rest of the branch is the same.. 😣

**Comment by laughedelic** [comment]
@eparejatobes @rtobes 
I'd like to discuss the format of rejected results before I launch it again. The problem is that there are sequences with **some** assignments rejected and with **all** assignments rejected. So far I tried to have rejected table+fasta output as similar to the accepted as possible, i.e.
- table: 2 columns
  - sequences ID
  - assigned taxas (separated with `;`)
- fasta: sequences in the same order as in the table

Now the questions are
- do we need FASTA of the rejected sequences at all? 
- if yes, does it have to correspond to the order of id's in the table?
  - if yes, you will have some intersection between accepted FASTA and rejected. It's not good or bad, but it's a bit confusing.
  - if no, you probably want to have only _completely_ rejected sequences (all assignments were rejected), to see how it influences the generated BlastDB.

If the rejected assignments are used only for manual analysis of what's rejected right/wrong, we probably don't need FASTA at all (which makes things simpler). Then we could think about the format of the output table, for example, it's probably useful to see _in one table (3 columns) for each sequence both accepted and rejected taxas_.

**Comment by eparejatobes** [comment]
I don't care about FASTA, as it is obtainable from the original one if needed. The output needs to cover for each sequence
1. its set of accepted taxonomy assignments
2. its set of rejected taxonomy assignments
3. whether _all_ assignments where rejected, and thus the sequence is dropped from the DB

**Comment by eparejatobes** [comment]
As for the pident, it should be _at least_ 99.0%. It's OK if a sequence gets no hits, as it won't be discarded then.

**Comment by laughedelic** [comment]
OK, so a table with three columns:

| Sequence ID | Accepted Taxas | Rejected Taxas |
| :-- | :-- | :-- |
| URS00000A4D66 | 1340418;1037936;1340422 | 442887 |
| URS00000A2E2A |  | 1122958;457173 |
| URS00000A2FB8 | 980870;980871 |  |

So that you can sort it by the second column and see those that are dropped from the DB (i.e. have empty cell in that column).

I'm also switching everywhere to CSV instead of TSV, just for uniformity.

**Comment by rtobes** [comment]
OK to the table. 
(We need a simple tool to obtain a fasta file with all the sequences corresponding to a list of RNAcentral IDs)

>  leave unique assignments without any filter

I think so, because it could be a rare taxa without similar sequences in the database (and/or not correctly placed in the taxonomy tree)

**Comment by eparejatobes** [comment]
@rtobes about http://rnacentral.org/rna/URS0000321FF1?tab=taxonomy
1. the ncbi taxonomy is OK
2. This one should be discarded, it comes from http://www.ncbi.nlm.nih.gov/nuccore/189913528 and they don't even know what it is. It looks Bacillus subtilis

**Comment by rtobes** [comment]
This is the only possibility for the lineage of the strain Bacillus sp. PK-5 using the NCBI taxonomy tree:
- Bacillus sp. PK-5
- Bacillus
- Bacillaceae
- Bacillales
- Bacilli
- Firmicutes

You can see here:
http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=1239&lvl=2&lin=f&keep=1&srchmode=1&unlock

The collapsed lineage without the  _Bacillales_ order rank probably come from Greengenes taxonomy.

**Comment by laughedelic** [comment]
Reran filter1 after #31, and got 3 new sequences filtered out:

| ID | Taxa |
| :-- | :-- |
| [URS0000252246](http://rnacentral.org/rna/URS0000252246/503006) | 503006 |
| [URS000028CAE7](http://rnacentral.org/rna/URS000028CAE7/61432) | 61432 |
| [URS0000879AFD](http://rnacentral.org/rna/URS0000879AFD/503006) | 503006 |

Their names (but not names of their ancestors) contain "unclassified". I guess, before only ancestors' names were checked.

Results are in `s3://resources.ohnosequences.com/era7bio/db.rna16s/0.9.0/filter1/`. 
366676 sequences in the output (out of 9386122, i.e. 3.91%).

**Comment by laughedelic** [comment]
Reran filter2. Results are in `s3://resources.ohnosequences.com/era7bio/db.rna16s/0.9.0/filter2/`. 
262331 seq-s in the output (71.54% of the filter1 output). No changes here.

**Comment by laughedelic** [comment]
Reran mg7 with pident 99.0% and filter3 with no touching single assignments. Results are in `s3://resources.ohnosequences.com/era7bio/db.rna16s/0.9.0/filter3/`.
261962 seq-s in the output, so _only 369_ sequences filtered out.

**Pull request merged**
