### PR TITLE
Release based on db.rnacentral v0.4.0

### PR DESCRIPTION
**Pull request by laughedelic**
- https://github.com/era7bio/db.rnacentral/releases/tag/v0.3.0

### CODE REVIEW

**Comment by laughedelic** [comment]
So I tried it with `r3.large` and `r3.2xlarge` instances with 40GB heap and it's still not enough. I think that the approach "let's launch a huge instance and do everything in memory" is a waste of resources. I'm going to rewrite filtering in some more optimal way.

**Comment by eparejatobes** [comment]
@laughedelic all the r3.xyz are under 1$/h spot. That's a perfectly reasonable cost for making a release.

**Comment by laughedelic** [comment]
The database is at `s3://resources.ohnosequences.com/era7bio/db.rna16s/0.7.0/`:
- `data/` contains filtered fasta and table
- `discarded/` contains discarded fasta and table
- `blastdb/` contains BLAST DB

It is strange though that the resulting table has more rows that the one from 0.6.4. Here are some rows that that I just discovered through `diff`:

```
URS0000592722|lcl|era7bio.db.rna16s 1723641
URS0000592A50|lcl|era7bio.db.rna16s 28151
URS00005931EC|lcl|era7bio.db.rna16s 305977
URS00005934D7|lcl|era7bio.db.rna16s 492670
URS00005A129A|lcl|era7bio.db.rna16s 454146
URS00005A1442|lcl|era7bio.db.rna16s 210830;1506
URS00005A6496|lcl|era7bio.db.rna16s 41950
URS00005A70BC|lcl|era7bio.db.rna16s 674045
URS00005AEE17|lcl|era7bio.db.rna16s 492670
```

[Here](https://gist.github.com/laughedelic/3895baaee6702e11e42f41e56ae7f0f3) is the full diff: 1278 lines.

**Comment by laughedelic** [comment]
Fixed the diff table (same link). In the end it has 1135 new lines 👍

**Pull request merged**
