### PR TITLE
review 0.10.0 data

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by eparejatobes** [comment]
Sorry about the blast noise, but I think it's worthwhile to take a look at it.

**Comment by eparejatobes** [comment]
The file to read is https://github.com/ohnosequences/db.rna16s/blob/review/data/48/docs/0.10.0-data-review/readme.md

**Comment by eparejatobes** [comment]
Please @rtobes @marina-manrique take a look

**Comment by rtobes** [comment]
I have reviewed the file and it is OK but, sorry, I don't understand the joke? about blast noise

**Comment by eparejatobes** [comment]
> about blast noise 

the BLAST files I added, which make for a pretty big diff here

**Comment by eparejatobes** [comment]
So about https://github.com/ohnosequences/db.rna16s/blob/review/data/48/docs/0.10.0-data-review/readme.md#conclusions; do we want all this before the paper? please vote here :)

**Comment by rtobes** [comment]
Thanks! I am reviewing the BLAST files now.

URS00008CCF2E:
This case is not clear because the RNAcentral assignment is to "Candidatus Hepatobacter penaei," This organisms is an intracellular pathogenic enteric bacterium in the hepatopancreas of the marine shrimp Penaeus vannamei (Crustacea: Decapoda):
- http://www.ncbi.nlm.nih.gov/pubmed/23241970
- http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3568585/figure/F1/

It is classified within _Rickettsiales_ order based on its 16S and gyrase sequences.
I would expect to find more similar sequences to 16S from Rickettsiales than to Pseudomonas.

**Comment by eparejatobes** [comment]
I expanded a bit on a simple way of implementing point 2. in the conclusions b22c8da

**Comment by rtobes** [comment]
Using the restriction of qcovs if you have in the database a reference sequence not correctly trimmed (with sequence regions not corresponding to 16S gene but to its flanking regions) the most similar sequences in the database will be those that casually include regions flanking 16S genes that can be similar. In that case the assignment is not based on the sequence of 16S gene but in the sequence of flanking regions. It could cause bad assignments. It could explain the similarity of URS00008CCF2E to Pseudomonas.

**Comment by eparejatobes** [comment]
I will do this again with 0.11 data.

**Comment by laughedelic** [comment]
Let's close it? Is there anything to merge?

**Comment by eparejatobes** [comment]
Yes, it can be closed.

**Pull request closed without merging**
